Faster and more strict do_test_qualified_name test, fix various manifest files

diff --git a/tools/internal/cge_shell_tests b/tools/internal/cge_shell_tests
--- a/tools/internal/cge_shell_tests
+++ b/tools/internal/cge_shell_tests
@@ -7,23 +7,47 @@ set -exuo pipefail
 
 cd "$CASTLE_ENGINE_PATH"
 
-# Test we don't have any examples with invalid qualified_name in CastleEngineManifest.xml .
-#
-# The CGE examples should all have
-#   qualified_name="io.castleengine.xxx.yyy.zzz"
-# (xxx.yyy.zzz being application name split into words and separated by dots).
-# See https://castle-engine.io/coding_conventions#_examples .
+# Test we don't have any projects with invalid qualified_name
+# in CastleEngineManifest.xml .
 do_test_qualified_name ()
 {
-  if grep --exclude='*~' --exclude='cge_shell_tests' --recursive --fixed-strings 'qualified_name="com.mycompany'; then
-    exit 1
-  fi
-  if grep --exclude='*~' --exclude='cge_shell_tests' --recursive --fixed-strings 'qualified_name="net.sourceforge'; then
-    exit 1
-  fi
-  if grep --exclude='*~' --exclude='cge_shell_tests' --recursive --fixed-strings 'qualified_name="io.sourceforge'; then
-    exit 1
-  fi
+  # For all projects: make sure they don't contain invalid qualified_name
+  # (it is OK to not have qualified_name at all, for now, for tools).
+  find . -name CastleEngineManifest.xml | while read -r CGE_MANIFEST_FILENAME; do
+    echo "Checking no invalid qualified name: ${CGE_MANIFEST_FILENAME}"
+    if grep --fixed-strings 'qualified_name="com.mycompany' "${CGE_MANIFEST_FILENAME}"; then
+      exit 1
+    fi
+    if grep --fixed-strings 'qualified_name="net.sourceforge' "${CGE_MANIFEST_FILENAME}"; then
+      exit 1
+    fi
+    if grep --fixed-strings 'qualified_name="io.sourceforge' "${CGE_MANIFEST_FILENAME}"; then
+      exit 1
+    fi
+
+    set +e # ignore wc exit code (wc may return 1 if no lines)
+    LINES=`grep --fixed-strings 'qualified_name="' "${CGE_MANIFEST_FILENAME}" | wc -l`
+    set -e
+
+    if [ "$LINES" '!=' '1' -a "$LINES" '!=' '0' ]; then
+      echo "Error: ${CGE_MANIFEST_FILENAME} has > 1 line with qualified_name"
+      exit 1
+    fi
+  done
+
+  # For examples/ projects: make sure they contain valid qualified_name.
+  #
+  # The CGE examples should all have
+  #   qualified_name="io.castleengine.xxx.yyy.zzz"
+  # (xxx.yyy.zzz being application name split into words and separated by dots).
+  # See https://castle-engine.io/coding_conventions#_examples .
+  find examples/ -name CastleEngineManifest.xml | while read -r CGE_MANIFEST_FILENAME; do
+    echo "Checking only valid: ${CGE_MANIFEST_FILENAME}"
+    if ! grep --fixed-strings 'qualified_name="io.castleengine' "${CGE_MANIFEST_FILENAME}"; then
+      echo "Error: ${CGE_MANIFEST_FILENAME} should have qualified_name starting with io.castleengine"
+      exit 1
+    fi
+  done
 }
 
 # Test that examples have no leftover "public domain" header.
