Run check_dependencies, check GNU make

diff --git a/.github/workflows/test-and-pack-runner-native.yml b/.github/workflows/test-and-pack-runner-native.yml
--- a/.github/workflows/test-and-pack-runner-native.yml
+++ b/.github/workflows/test-and-pack-runner-native.yml
@@ -91,6 +91,11 @@ jobs:
       run: lazbuild --version
     - name: (Info) Make version
       run: make --version
+    # Make sure we got GNU Make, not Embarcadero make.
+    # This is important, as Delphi installer inserts Embarcadero make into PATH,
+    # earlier than Cygwin's. It has to be corrected after installation.
+    - name: (Info) Check GNU Make
+      run: if make -version 2>&1 | grep -i "GNU Make" -; then echo "OK, make from GNU"; else echo "ERROR, make not from GNU!"; exit 1; fi
 
     - name: Build Tools
       run: |
@@ -120,6 +125,8 @@ jobs:
         lazbuild packages/castle_components.lpk
         lazbuild packages/castle_editor_components.lpk
         lazbuild packages/alternative_castle_window_based_on_lcl.lpk
+
+    # TODO: also run examples-laz here
 
     - name: Build and Install PasDoc
       run: |
